version: '3'
services:
  xboard:
    image: ghcr.io/dawenhaozx/xboard:latest
    container_name: xboard
    restart: unless-stopped
    environment:
      - docker=true
    ports:
      - "7001:7001"
    volumes:
      - ./.env:/www/.env
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=xboard
    volumes:
      - ./mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis-data:/data