version: '3'
services:
  xboard:
    image: ghcr.io/dawenhaozx/xboard:latest
    volumes:
      - ./.env:/www/.env
      - ./.docker/.data/:/www/.docker/.data/
      # - ./config/v2board.php:/www/config/v2board.php
      - redis-socket:/run/redis-socket # 挂载socket
    environment:
      - docker=true #用于给安装脚本判断是否为docker环境
    links:
      - mysql
    depends_on:
      - redis
    ports:
      - '7001:7001'
    restart: always

  mysql:
    image: arm64v8/mysql:latest
    volumes:
      - './mysql:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234565'
      MYSQL_DATABASE: 'xboard'
      
  redis:
    build: 
      context: .docker/services/redis
    restart: always
    volumes:
      - ./.docker/.data/redis:/data/ # 挂载redis持久化数据
      - redis-socket:/run/redis-socket # 挂载socket
volumes:
  redis-socket:
